# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a7bd133a51153b9b0d5f67da7160f83123cc1f9bf1f0fd4911d11a20d3b814fdcce80b20b9f9a0ccdaaca38549c791482d195e727e65db05119b616627bf80a

test:
  secret_key_base: 463946f41112eff0e472338d8c0a1aad96f7e5be1798d782f4fcc43fcfa4b34cc4cdbe10f947b43d14c881b607c0d65ad290ef386640237aa7a2374e8725d876

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
